
/* 테이블 */
CREATE TABLE TBL_JOONGGO(
	JOONGGO_PRODUCTNUMBER NUMBER CONSTRAINT PK_JOONGGO PRIMARY KEY,
	JOONGGO_NAME VARCHAR2(1000),
	JOONGGO_PRICE NUMBER,
	JOONGGO_ADDRESS VARCHAR2(1000),
	JOONGGO_URL VARCHAR2(1000)
);

DROP TABLE TBL_JOONGGO;


CREATE TABLE TBL_DANGGEUN(
	DANGGEUN_PRODUCTNUMBER NUMBER CONSTRAINT PK_DANGGEUN PRIMARY KEY,
	DANGGEUN_NAME VARCHAR2(1000),
	DANGGEUN_PRICE NUMBER,
	DANGGEUN_ADDRESS VARCHAR2(1000),
	DANGGEUN_URL VARCHAR2(1000)
);

DROP TABLE TBL_DANGGEUN;

SELECT * FROM TBL_CATEGORY;

SELECT * FROM TBL_DANGGEUN ORDER BY DANGGEUN_PRICE ASC;

CREATE TABLE TBL_BUNGAE(
	BUNGAE_PRODUCTNUMBER NUMBER CONSTRAINT PK_BUNGAE PRIMARY KEY,
	BUNGAE_NAME VARCHAR2(1000),
	BUNGAE_PRICE NUMBER,
	BUNGAE_ADDRESS VARCHAR2(1000),
	BUNGAE_URL VARCHAR2(1000)
);

DROP TABLE TBL_BUNGAE;

CREATE TABLE TBL_TOTAL(
	TOTAL_PRODUCTNUMBER NUMBER CONSTRAINT PK_TOTAL PRIMARY KEY,
	TOTAL_COMPANYNAME VARCHAR2(1000),
	TOTAL_NAME VARCHAR2(1000),
	TOTAL_PRICE NUMBER,
	TOTAL_ADDRESS VARCHAR2(1000),
	TOTAL_URL VARCHAR2(1000)
);

DROP TABLE TBL_TOTAL;


SELECT USERS_ID, ITEM_NAME, ITEM_PRICE, ITEM_ADDRESS, ITEM_URL, ITEM_VIEW
FROM TBL_BASKET WHERE USERS_ID = 1;

CREATE SEQUENCE JOONGGO_SEQ;
CREATE SEQUENCE DANGGEUN_SEQ;
CREATE SEQUENCE BUNGAE_SEQ;
CREATE SEQUENCE TOTALRESULT_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE
NOCACHE
NOORDER;




CREATE SEQUENCE USERS_SEQ;
CREATE SEQUENCE USERSDATA__SEQ;
DROP SEQUENCE TOTAL_SEQ;


CREATE TABLE TBL_USERS(
USER_NUMBER NUMBER,
USER_ID VARCHAR2(1000) CONSTRAINT PK_USERS PRIMARY KEY,
USER_PW VARCHAR2(1000),
USER_CG VARCHAR2(1000)
);

DROP TABLE TBL_USERS;

SELECT * FROM TBL_JOONGGO;
SELECT * FROM TBL_DANGGEUN;
SELECT * FROM TBL_BUNGAE;
SELECT *FROM TBL_TOTAL;
SELECT *FROM TBL_USERS;
SELECT *FROM TBL_USERSDATA;

DROP TABLE TBL_TOTAL;

CREATE TABLE TBL_USERSDATA(
   USERSDATA_PRODUCTNUMBER NUMBER CONSTRAINT USERSDATA PRIMARY KEY,
   USERSDATA_ID VARCHAR2(1000),
   USERSDATA_KEY VARCHAR2(1000),
   CONSTRAINT FK_ID FOREIGN KEY(USERSDATA_ID) REFERENCES TBL_USERS(USER_ID)
);

DROP TABLE TBL_USERSDATA;

/*카테고리*/
CREATE TABLE TBL_CATEGORY(
	CATEGORY_NUMBER NUMBER CONSTRAINT PK_CATEGORY PRIMARY KEY,
	CATEGORY_SEMICATEGORY VARCHAR2(1000)
);


CREATE SEQUENCE CATEGORY_SEQ;
SELECT * FROM TBL_CATEGORY;

DROP TABLE TBL_CATEGORY;
DROP SEQUENCE CATEGORY_SEQ;



	
	
	
CREATE TABLE TBL_BASKET(
      ITEM_NUMBER NUMBER  CONSTRAINT PK_BASKET PRIMARY KEY,
      USERS_ID VARCHAR2(1000),
      ITEM_NAME VARCHAR2(1000) UNIQUE,
      ITEM_PRICE VARCHAR2(1000),
      ITEM_ADDRESS VARCHAR2(1000),
      ITEM_URL VARCHAR2(1000),
      ITEM_VIEW VARCHAR2(1000),
      CONSTRAINT FK_BASKET FOREIGN KEY(USERS_ID) REFERENCES TBL_USERS(USER_ID)
   );

DROP TABLE TBL_BASKET ;

CREATE SEQUENCE BASKET_SEQ;

SELECT * FROM TBL_BASKET;	



DROP TABLE TBL_CATEGORY;


INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (1,'캐쥬얼,맨투맨,바지,코트,패딩,속옷,후드,자켓,점퍼,잠옷,기타의류,골프의류,티셔츠,청바지,조끼,가디건');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (2,'스웨터,블라우스,셔츠,치마,스커트,여성,등산의류,패딩,점퍼,코트,맨투맨,후드티,후드집업,티셔츠,블라우스,셔츠,바지,청바지,반바지,치마,원피스,가디건,니트,자켓,정장,점프수트,조끼,베스트,트레이닝,언더웨어,홈웨어,테마,이벤트');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (3,'셔츠,정장,남성 수영복,남성 등산의류,패딩,점퍼,코트,맨투맨,후드티,후드집업,티셔츠,가디건,니트,스웨터,바지,청바지,반바지,자켓,조끼,베스트,트레이닝,언더웨어,홈웨어,테마,이벤트');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (4,'여성화,남성화,운동화,등산화,신발');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (5,'여성가방,핸드백,남성가방,백팩,여행용,캐리어,기타가방,클러치백,숄더백,크로스백,토트백');
 INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (6,'남성용 시계,여성용 시계,시계,피어싱,펜던트,기타쥬얼리');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (7,'귀걸이,목걸이,팔찌,발찌,반지,주얼리,쥬얼리');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (8,'화장품,스킨,메이크업,마스크 팩, 마스크팩, 클렌징,남성용 화장품,여성용 화장품,향수,로션,스킨케어,색조메이크업,베이스메이크업,바디,헤어케어향수,아로마네일아트,케어미용소품,기기다이어트,이너뷰티,남성 화장품');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (9,'스킨케어,메이크업,팩,클렌징,화장품,향수,화장아이라이너,브로우,아이섀도우,마스카라,립틴트,립밤,립글로즈,립스틱,치크,블러셔,기타색조메이크업,BB,CC크림,쿠션팩트,파운데이션,파우더,팩트프라이머,컨실러,기타베이스메이크업,스킨,로션,마스크,에센스,크림,BB크림,선케어,왁스,올인원,세트,기타남성화장품');
 INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (10,'샴푸,린스,트리트먼트,비듬,헤어 오일,염색,탈색,가발,롤,빗');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (11,'출산용품,임부용품,수유용품,기저귀,티슈,분유,이유식,베이비의류02세,원피스,우주복,슈트,유아상의,자켓,점퍼,유아하의,정장,드레스,베이비수영복,유아내의,속옷,기타베이비의류');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (12,'2세,6세,7세');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (13,'유아용 의류,아동 수영복,아동복,유아용 우의,티셔츠,블라우스,남방,가디건,조끼,니트,스웨터,자켓,점퍼,코트,정장,원피스,상하복세트,팬츠,스커트,치마,수영복,속옷,잠옷,기타여아의류,티셔츠,셔츠,남방,가디건,조끼,니트,스웨터,자켓,점퍼,코트,정장,상하복세트,팬츠,수영복,속옷,잠옷,기타남아의류');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (14,'유모차,유아용 띠,신발,가방,모자,시계,액세서리,양말,기타유아동신발,잡화');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (15,'유아용 도서,유아용 완구,유아용 퍼즐,놀이터 완구,운동용 완구,기타,인형(유아용),교육완구,CD,DVD,퍼즐,블록,자전거,승용완구,스포츠완구,물놀이용품,볼텐트,놀이터,신생아완구');
  INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (16,'가정가구,침실,거실,서재,기타,소품,꽃,원예,수공예품,침실가구,거실가구,침구,사무용가구');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (17,'커튼,카펫,조명,수납,선반,시계');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (18,'인테리어,액자');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (19,'에어프라이어,전자레인지,로봇청소기,드라이기,고데기,리모콘,면도기,안마기,선풍기,살균기,삼성,lg');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
 (20, '냉장고, 김치냉장고, 식기세척기 , 진공청소기, 청소기, 세탁기, 드럼세탁기, 일반세탁기, TV, 벽걸이TV, 에어컨, 벽걸이에어컨, 오븐, 건조기, 스타일러, 드럼세탁기, 일반세탁기, 안마의자, 공기청정기, 의류 관리기');

INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
 (21, '냉장고, 김치냉장고, 오븐, 에어프라이, 에어프라이어, 레인지, 전자레인지, 전기레인지, 인덕션, 토스터, 밥솥, 전기밥솥, 식기세척기, 믹서기');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
 (22, '모바일, 휴대폰, 스마트폰, 태블릿, 아이폰, 갤럭시, 삼성, 애플, 스마트 워치, 웨어러블, 피쳐폰, 핸드폰케이스, 케이스, 보호필림, 보조배터리, 충전기, C타입, 휴대폰 액세서리, 휴대폰 주변기기, 기타 모바일 기기');

INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
 (23, 'PC, 컴퓨터, 데스크탑, 노트북, 맥북, 게이밍, 게이밍 컴퓨터, 조립 컴퓨터, 조립컴, 일체형PC, CPU, 라이젠, 인텔, 메인보드, 아수스, 기가바이트, MSI, 램, RAM, 그래픽카드, 지포스, RTX, GTX, AMD, HDD, SSD, 하드디스크, USB, 키보드, 마우스, 스피커, 케이스, 쿨러, 파워, 팬, 프린터, 복합기, 잉크, 공유기, 랜카드, 소프트웨어');

INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
 (24, '게임, 닌텐도, 스위치, 3DS, 플레이스테이션, 플스, XBOX, 엑스박스, 엑박, PC게임, 패키지게임, 한정판, 게임 계정, 리세계');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
 (25, '카메라, DSLR, 미러리스, 디지털카메라, 디카, 필름카메라, 즉석카메라, 아날로그카메라, 중형카메라, 캠코더, 디지털 캠코더, 렌즈, 필터, 컨버터, 카메라렌즈, 메모리, 삼각대, 조명, 플래시');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
 (26, '축구, 야구, 농구, 유니폼, 축구공, 야구공, 농구공, 글러브, 배트, 야구방망이, 축구화, 골프, 라켓, 테니스, 배드민턴, 셔틀콕, 스키, 보드, 수영, 수영복, 비키니, 스쿠버, 다이빙');

INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
(27, '헬스, 헬스기구, 헬스용품, 아령, 덤벨, 슬리브, 요가, 필라테스, 필라테스용품, 요가매트, 보충, 보충제, 보조제');


INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
 (28, '스키, 스키복, 보드, 요트, 스노보드, 수상스키, 고글, 수영, 수영복, 잠수, 여성수영복, 비키니, 남성수영복, 래쉬가드, 아동수영복, 스쿠버, 다이빙');



INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
 (29, '자전거, 사이클, 하이브리드, 픽시, 미니벨로, MBT, 산악자전거, 전기자전거, 아동자전거, 세발자전거, 인라인, 스케이트, 인라인스케이트, 보드, 스케이트보드 로드바이크, 전동기, 전동 킥보드, 킥보드, 자전거용품, 자전거부품, 자전거공구, 자전거체인, 자전거 바퀴, 자전거 액세서리');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (30,'캠핑,텐트,취사,등산,클라이밍,수상');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (31,'바다,민물,낚시,루어,플라이');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (32,'등산,남성등산복,여성등산복,등산화,트레킹화,암벽,클라이밍');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (33,'골프,골프체,골프공,필드');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (34,'피규어,인형,로봇,프라모델,레고,조립,드론,RC,카드');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (35,'악기,미술,골동품,작품');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (36,'학습지,책,도서,인쇄,간행물,PDF,전공서,잡지,스캔본,시,소설,자기계발,교양,인문,경제,경영,학습,사전,참고서,아동,어린이,만화,예술,디자인,여행,취미,레저,건강,사회,정치,법,과학,IT,간행물,기타');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (37,'CD,DVD,티켓,상품권,쿠폰,음반,악기');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (38,'자동차,휴대용 방향제,세차,엔진오일,엔진,와이퍼,타이어,바퀴,현대,기아,르노,네비게이션,블랙박스,튜닝,오디오');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (39,'식품,샴푸,린스,바디,로션,밀키트,DIY,리폼용품,공구,');
   INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (40,'강아지,고양이,반려,원예,용품,사료,간식,고양이 용품,고양이 사료,간식,고양이,반려동물 용품,반려동물 사료,간식');
INSERT INTO HR.TBL_CATEGORY (CATEGORY_NUMBER,CATEGORY_SEMICATEGORY) VALUES
    (41,'비행기,여행,캠핑,텐트,취사,티켓');
    
   
   
   
   
   
   
   
SELECT *FROM TBL_TOTAL;
SELECT *FROM TBL_USERS;
SELECT *FROM TBL_USERSDATA;
SELECT * FROM TBL_BASKET;
SELECT * FROM TBL_CATEGORY;