/*회원*/

/*
 * 회원번호
 * 아이디
 * 이름
 * 비밀번호
 * 전화번호
 * 닉네임
 * 이메일
 * 주소
 * 생년월일
 * 성별
 * 추천인 아이디
 * 직업
 * 
 * */

CREATE TABLE TBL_USER(
	USER_NUMBER NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_ID VARCHAR2(1000) UNIQUE NOT NULL,
	USER_NAME VARCHAR2(1000) NOT NULL,
	USER_PASSWORD VARCHAR2(1000) NOT NULL,
	USER_PHONE VARCHAR2(1000) UNIQUE NOT NULL,
	USER_NICKNAME VARCHAR2(1000) NOT NULL,
	USER_EMAIL VARCHAR2(1000) UNIQUE NOT NULL,
	USER_ADDRESS VARCHAR2(1000),
	USER_BIRTH_DATE DATE,
	USER_GENDER VARCHAR2(100) DEFAULT 'N' CONSTRAINT BAN_GENDER CHECK(USER_GENDER IN('M', 'W', 'N')),
	USER_RECOMMEND_ID VARCHAR2(1000),
	USER_JOB VARCHAR2(1000)
);

DROP TABLE TBL_USER;

SELECT * FROM TBL_USER;


CREATE SEQUENCE SEQ_USER;

INSERT INTO TBL_USER
(USER_NUMBER, USER_ID, USER_NAME, USER_PASSWORD, USER_PHONE, USER_NICKNAME, USER_EMAIL, USER_ADDRESS, USER_BIRTH_DATE, USER_GENDER, USER_RECOMMEND_ID, USER_JOB)
VALUES(SEQ_USER.NEXTVAL, 'hds', '한동석', '1234', '01012341234', 'zl존동석123', 'tedhan1204@gmail.com', '경기도 남양주시', '2003-12-04', 'N' , '', '교육');
